myexcel/urls.py
from django.urls import path
from . import views, admin_views

app_name = 'myexcel'
urlpatterns = [
    # path('', admin_views.login, name='login'),
    # path('admin/myexcel/project/', admin_views.change_list, name='project'),
    path('', views.project, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/excel/', views.excel, name='excel'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from myexcel.admin_views import change_list

urlpatterns = [
    path('', include('myexcel.urls')),
    path('admin/', admin.site.urls),
]

myexcel/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import datetime

# Create your models here.
class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True)
    project_name = models.CharField('项目名称', max_length=50)
    project_text = models.TextField('项目描述', null=True)
    project_charge = models.CharField('项目负责人', max_length=50, default='赵旻')
    pub_date = models.DateTimeField('date published', auto_now=True)

    def __str__(self):
        return self.project_name

class Table(models.Model):
    table_name = models.CharField('excel表名', max_length=50)
    table_en_name =  models.CharField('英文名', max_length=50, null=True)
    table_row = models.IntegerField('行数', default=10)
    pub_date = models.DateTimeField('date published', auto_now=True)

    def __str__(self):
        return self.table_name

class ProjectTable(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, db_index=True)
    table = models.ForeignKey(Table, on_delete=models.CASCADE, db_index=True)

class Column(models.Model):
    table = models.ForeignKey(Table, on_delete=models.CASCADE, db_index=True)
    column_name = models.CharField('列名', max_length=50)
    column_en_name = models.CharField('英文名', max_length=50)
    parameter = models.CharField('参数名', max_length=10, null=True)
    formula = models.CharField('公式', max_length=100, null=True)
    dropdown = models.ForeignKey(Value, on_delete=models.CASCADE, null=True)
    default = models.CharField('默认值', max_length=10, null=True)
    prompt = models.CharField('提示', max_length=100, null=True)
    must = models.BooleanField('是否必填', default=True)
    pub_date = models.DateTimeField('date published', auto_now=True)

    def __str__(self):
        return self.column_name

class Value(models.Model):
    project_table = models.ForeignKey(ProjectTable, on_delete=models.CASCADE, db_index=True)
    value =  models.TextField('值', null=True)
    pub_date = models.DateTimeField('date published', auto_now=True)

    def __str__(self):
        return self.value

myexcel/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from .models import Project,ProjectTable, Table, Column, Value
from django.contrib.auth.models import User
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from mysite.common.response import json_response
import json

@login_required(redirect_field_name='', login_url='/admin/login/')
def project(request):
    project_list = Project.objects.filter(user=request.user)
    context = {'list': project_list}
    return render(request, 'myexcel/index.html', context)

@login_required(redirect_field_name='', login_url='/admin/login/')
def detail(request, pk):
    tables = ProjectTable.objects.filter(project=pk).all()
    return render(request, 'myexcel/tables.html', {'list': tables})

@login_required(redirect_field_name='', login_url='/admin/login/')
def excel(request, pk):
    context = {}
    project_table = ProjectTable.objects.get(pk=pk)
    if request.POST:
        data = request.POST['data']
        value = Value(value=json.dumps(data), project_table=project_table)
        value.save()
        return json_response('保存成功！')
    else:
        data = Value.objects.filter(project_table=project_table)
        if data:
            data = data[0].value
        else:
            data = json.dumps("[[]]")
    c = []

    columns = Column.objects.filter(table=project_table.table)
    for column in columns:
        c.append({'title': column.column_name, 'width': column.width})
    context['columns'] = json.dumps(c)
    context['minDimensions'] = json.dumps([len(c),project_table.table.table_row])
    context['data'] = data
    return render(request, 'myexcel/excel.html', context)

myexcel/templates/myexcel/excel.html
 {% load static %}
<script src="{% static 'jquery.min.js' %}"></script>

<script src="{% static '/jexcel/dist/jexcel.js' %}"></script>
<link rel="stylesheet" href="{% static '/jexcel/dist/jexcel.css' %}" type="text/css" />
<script src="{% static '/jsuites/dist/jsuites.js' %}"></script>
<link rel="stylesheet" href="{% static '/jsuites/dist/jsuites.css' %}" type="text/css" />

<div id="spreadsheet"></div>

<input type="button" value="保存" onclick="submit()" /><i id="ret"></i></div>
		{% csrf_token %}

<script>
var options = {
    data:JSON.parse({{ data|safe }}),
    columns:{{ columns|safe }},
    minDimensions:{{ minDimensions|safe }},
}
$('#spreadsheet').jexcel(options);
function submit() {
    txt = JSON.stringify($('#spreadsheet').jexcel('getData', false))
    csrf = $("input[name='csrfmiddlewaretoken']").val()
    $.post("{% url 'myexcel:excel' 3 %}", {data:txt, csrfmiddlewaretoken:csrf}, function (result) {
        $("#ret").html(result.data)
    })
}
</script>

myexcel/templates/myexcel/index.html
{% if list %}
    <ul>
    {% for var in list %}
        <li><a href="{% url 'myexcel:detail' var.id %}">{{ var.project_name }}</a> </li>
    {% endfor %}
    </ul>
{% else %}

{% endif %}

myexcel/templates/myexcel/tables.html
{% if list %}
    <ul>
    {% for var in list %}
        <li><a href="{% url 'myexcel:excel' var.id %}">{{ var.table.table_name }}</a> </li>
    {% endfor %}
    </ul>
{% else %}

{% endif %}

myexcel/templates/myexcel/test.html
 {% load static %}
<script src="{% static 'jquery.min.js' %}"></script>

<script src="{% static '/jexcel/dist/jexcel.js' %}"></script>
<link rel="stylesheet" href="{% static '/jexcel/dist/jexcel.css' %}" type="text/css" />
<script src="{% static '/jsuites/dist/jsuites.js' %}"></script>
<link rel="stylesheet" href="{% static '/jsuites/dist/jsuites.css' %}" type="text/css" />

<div id="spreadsheet"></div>

<input type="button" value="保存" onclick="submit()" /><i id="ret"></i></div>
		{% csrf_token %}

<script>
var options = {
    data:JSON.parse({{ data|safe }}),
    columns:{{ columns|safe }},
    minDimensions:{{ minDimensions|safe }},
}
$('#spreadsheet').jexcel(options);
function submit() {
    txt = JSON.stringify($('#spreadsheet').jexcel('getData', false))
    csrf = $("input[name='csrfmiddlewaretoken']").val()
    $.post("{% url 'myexcel:excel' 3 %}", {data:txt, csrfmiddlewaretoken:csrf}, function (result) {
        $("#ret").html(result.data)
    })
}
</script>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Hello World!</h1>
    <p>Django测试</p>
    {% block mainbody %}
        <p>original</p>
    {% endblock %}
</body>
</html>

templates/hello.html
{% extends "base.html" %}

{% block mainbody %}
<p>继承了 base.html 文件</p>
    {{ hello }}
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="zh">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>jExcel-类似Excel的jquery电子表格插件</title>
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'jexcel/css/normalize.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'jexcel/css/jq22-demo.css' %}">
	<link rel="stylesheet" href="{% static 'jexcel/dist/css/jquery.jexcel.css' %}" type="text/css" />
	<style type="text/css">
		#my{
			width: 600px;
			margin: 50px auto;
		}
		.code{
			width: 800px;
			margin: 0 auto;
		}
	</style>
</head>
<body>
	<div class="jq22-container">
		<div id="my"></div>
        <div><button id="submit" onclick="submit(this)" style="margin-left:60%">上传</button> <i id="ret"></i></div>
		{% csrf_token %}
	</div>


	<script src="http://www.jq22.com/jquery/jquery-1.10.2.js"></script>
	<script type="text/javascript" src="{% static 'jexcel/dist/js/jquery.jexcel.js' %}"></script>
	<script type="text/javascript">
		data = JSON.parse({{ data|safe }});
		$('#my').jexcel({ data:data, colWidths: [ 300, 80, 100 ] });
        function submit() {
            txt = JSON.stringify($('#my').jexcel('getData', false))
            csrf = $("input[name='csrfmiddlewaretoken']").val()
            $.post("/index", {data:txt, csrfmiddlewaretoken:csrf}, function (result) {
                $("#ret").html(result.data)
            })
        }
	</script>
</body>
</html>

templates/post.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>菜鸟教程(runoob.com)</title>
</head>
<body>
    <form action="/search-post" method="post">
        {% csrf_token %}
        <input type="text" name="q">
        <input type="submit" value="Submit">
    </form>

    <p>{{ rlt }}</p>
<script>

</script>
</body>
</html>